server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookstarter
    username: admin
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: orders

app:
  jwt:
    secret-key: topsecretkey123rieubherotuh3498th398gh395g8h598gh4g8gidufghdifughi43gg4334t3h4gi34uhgi35uhgi35ughi45ugho98dhf98bhg
  order-board:
    path: https://cookstarter-order-board.herokuapp.com
    add: /add
  customer-service:
    path: https://cookstarter-users-service.herokuapp.com
    get-info: /users/info/%s
  restaurant-service:
    path: https://cookstarter-restaurant-service.herokuapp.com
    get-dish: /dish/get/%s
